In [1]:
import pandas as pd
from itertools import combinations
PATNOs = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/PD_CSV_CLEAN/Relevant_presnece_PATNO', dtype=str)['PATNO'].tolist()
print(f"Total PATNOs to process-subjects with PD and UPDRS3: {len(PATNOs)}")

Total PATNOs to process-subjects with PD and UPDRS3: 1056

# ANALYSIS SUBJECT VISIT MODALITY

In [2]:
list_modalities = ['DaTScan', 'MRI_PD', 'MRI_T1', 'MRI_T2','fMRI', 'DTI', 'PET','CT']
result_parwise = list(combinations(list_modalities, 2))
print(result_parwise)

[('DaTScan', 'MRI_PD'), ('DaTScan', 'MRI_T1'), ('DaTScan', 'MRI_T2'), ('DaTScan', 'fMRI'), ('DaTScan', 'DTI'), ('DaTScan', 'PET'), ('DaTScan', 'CT'), ('MRI_PD', 'MRI_T1'), ('MRI_PD', 'MRI_T2'), ('MRI_PD', 'fMRI'), ('MRI_PD', 'DTI'), ('MRI_PD', 'PET'), ('MRI_PD', 'CT'), ('MRI_T1', 'MRI_T2'), ('MRI_T1', 'fMRI'), ('MRI_T1', 'DTI'), ('MRI_T1', 'PET'), ('MRI_T1', 'CT'), ('MRI_T2', 'fMRI'), ('MRI_T2', 'DTI'), ('MRI_T2', 'PET'), ('MRI_T2', 'CT'), ('fMRI', 'DTI'), ('fMRI', 'PET'), ('fMRI', 'CT'), ('DTI', 'PET'), ('DTI', 'CT'), ('PET', 'CT')]

## V04

### Data Modalities

#### CT

In [3]:
ct_v04=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/CT/CT_images_V04.csv',sep=';', dtype=str)
ct_v04 = ct_v04[ct_v04['Subject ID'].isin(PATNOs)]
print(f"Total PATNOs with CT V04 images: {ct_v04['Subject ID'].nunique()}")
ct_v04.head(20)

Total PATNOs with CT V04 images: 6

   Subject ID Visit ID Sex   Age          Description      Type
8       40671      NaN   M  61.2      H30S med smooth  Original
9       40671      NaN   M  61.2  AC_CT H19S v smooth  Original
10      40781      NaN   M  50.9                AC_CT  Original
13      41767      NaN   F  78.1                AC_CT  Original
14      41829      NaN   M  71.2                AC_CT  Original
15      42710      NaN   F  65.8                AC_CT  Original
16      58783      NaN   F  50.8  CT Brain  3.0  H31s  Original

#### DaTScan

In [4]:
datscan_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DaTScan/DaTScan_image_V04.csv', sep=';',dtype=str)
datscan_v04 = datscan_v04[datscan_v04['Subject ID'].isin(PATNOs)]
print(f'Total PATNOs with DaTScan V04 images: {datscan_v04["Subject ID"].nunique()}')
datscan_v04.head(3)

Total PATNOs with DaTScan V04 images: 576

,Subject ID,Visit ID,Sex,Age,Description,Type
0,100001,V04,M,68.5,DaT Brain Tomo,Original
1,100001,NaN,M,68.5,Reconstructed DaTSCAN <- DaT Brain Tomo,Pre-processed
2,100002,NaN,M,59.7,Brain Tomo,Original

In [5]:
datscan_v04.head(3)

,Subject ID,Visit ID,Sex,Age,Description,Type
0,100001,V04,M,68.5,DaT Brain Tomo,Original
1,100001,NaN,M,68.5,Reconstructed DaTSCAN <- DaT Brain Tomo,Pre-processed
2,100002,NaN,M,59.7,Brain Tomo,Original

#### fMRI

In [6]:
fmri_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/fMRI/fMRI_images_V04.csv', sep=';',dtype=str)
fmri_v04 = fmri_v04[fmri_v04['Subject ID'].isin(PATNOs)]
print(f'Total PATNOs with fMRI V04 images: {fmri_v04["Subject ID"].nunique()}')
fmri_v04.head(3)

Total PATNOs with fMRI V04 images: 182

  Subject ID Visit ID Sex   Age Description      Type
0     100005      V04   M  53.8   rsfMRI_RL  Original
1     100005      NaN   M  53.8  rsfMRI_L_R  Original
2     100006      NaN   F  56.7   rsfMRI_RL  Original

In [7]:
fmri_v04.head(3)

  Subject ID Visit ID Sex   Age Description      Type
0     100005      V04   M  53.8   rsfMRI_RL  Original
1     100005      NaN   M  53.8  rsfMRI_L_R  Original
2     100006      NaN   F  56.7   rsfMRI_RL  Original

#### DTI

In [8]:
dti_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DTI/DTI_images_V04.csv', sep=';',dtype=str)
dti_v04 = dti_v04[dti_v04['Subject ID'].isin(PATNOs)]
print(f'Total PATNOs with DTI V04 images: {dti_v04["Subject ID"].nunique()}')
dti_v04.head(3)

Total PATNOs with DTI V04 images: 351

  Subject ID Visit ID Sex   Age    Description      Type
0     100005      V04   M  53.8  DTI_30dir L-R  Original
1     100005      NaN   M  53.8  DTI_30dir R-L  Original
2     100006      NaN   F  56.7  DTI_30dir R-L  Original

#### MRI T1

In [9]:
mri_T1_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T1/MRI_T1_images_V04.csv', sep=';',dtype=str)
mri_T1_v04 = mri_T1_v04[mri_T1_v04['Subject ID'].isin(PATNOs)]
print(f'Total PATNOs with MRI T1 V04 images: {mri_T1_v04["Subject ID"].nunique()}')
mri_T1_v04.head(3)

Total PATNOs with MRI T1 V04 images: 416

  Subject ID Visit ID Sex   Age Description      Type
0     100005      V04   M  53.8   2D GRE-MT  Original
1     100006      NaN   F  56.7   2D GRE-MT  Original
2     100007      NaN   M  68.4   2D GRE-MT  Original

#### MRI T2

In [10]:
mri_T2_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T2/MRI_T2_images_V04.csv', sep=';',dtype=str)
mri_T2_v04 = mri_T2_v04[mri_T2_v04['Subject ID'].isin(PATNOs)]
print(f'Total PATNOs with MRI T2 V04 images: {mri_T2_v04["Subject ID"].nunique()}')
mri_T2_v04.head(3)

Total PATNOs with MRI T2 V04 images: 415

  Subject ID Sex   Age  Description      Type
0     100005   M  53.8  3D T2 FLAIR  Original
1     100006   F  56.7  3D T2 FLAIR  Original
2     100007   M  68.4  3D T2 FLAIR  Original

#### MRI PD

In [11]:
mri_PD_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI PD/MRI_PD_images_V04.csv', sep=';',dtype=str)
mri_PD_v04 = mri_PD_v04[mri_PD_v04['Subject ID'].isin(PATNOs)]
print(f'MRI PD V04 shape: {mri_PD_v04.shape}')
mri_PD_v04.head(3)

MRI PD V04 shape: (645, 6)

  Subject ID Visit ID Sex   Age      Description      Type
0     100005      V04   M  53.8  3D T1 _weighted  Original
1     100006      NaN   F  56.7  3D T1 _weighted  Original
2     100007      NaN   M  68.4  3D T1 _weighted  Original

#### PET

In [12]:
pet_v04 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/PET/PET_image_V04.csv', sep=';',dtype=str)
pet_v04 = pet_v04[pet_v04['Subject ID'].isin(PATNOs)]
print(f'PET V04 shape: {pet_v04.shape}')
pet_v04.head(3)

PET V04 shape: (94, 6)

  Subject ID Visit ID Sex   Age                     Description      Type
0     100001      V04   M  68.5  AV 133 Delay 4i/16s-UNFILTERED  Original
1     100001      NaN   M  68.5    AV 133 Delay 4i/16s-FILTERED  Original
2     100001      NaN   M  68.5             TX Scan 4min 4i/16s  Original

### Combinations of modalities in V04

In [13]:

# =========================
# Diccionario de modalidades
# =========================
dict_modal_subjects = {
    'DaTScan': datscan_v04['Subject ID'].unique(),
    'fMRI': fmri_v04['Subject ID'].unique(),
    'DTI': dti_v04['Subject ID'].unique(),
    'MRI_PD': mri_PD_v04['Subject ID'].unique(),
    'MRI_T1': mri_T1_v04['Subject ID'].unique(),
    'MRI_T2': mri_T2_v04['Subject ID'].unique(),
    'PET': pet_v04['Subject ID'].unique(),
    'CT': ct_v04['Subject ID'].unique()
}

dict_images_subjects = {
    'DaTScan': datscan_v04['Subject ID'].shape[0],
    'fMRI': fmri_v04['Subject ID'].shape[0],
    'DTI': dti_v04['Subject ID'].shape[0], 
    'MRI_PD': mri_PD_v04['Subject ID'].shape[0],
    'MRI_T1': mri_T1_v04['Subject ID'].shape[0],
    'MRI_T2': mri_T2_v04['Subject ID'].shape[0],  # modalidad vacía
    'PET': pet_v04['Subject ID'].shape[0],
    'CT': ct_v04['Subject ID'].shape[0]
}

list_modalities = list(dict_modal_subjects.keys())

# =========================
# DataFrame 1: intersecciones entre modalidades (MultiIndex)
# =========================
combinations_keys = list(combinations(list_modalities, 2))
index = pd.MultiIndex.from_tuples(
    combinations_keys,
    names=['Modality_1', 'Modality_2']
)
df = pd.DataFrame(index=index, columns=['V04','V06','V08','V10'], dtype=int)

for comb in combinations_keys:
    set_1 = set(dict_modal_subjects[comb[0]])
    set_2 = set(dict_modal_subjects[comb[1]])
    common_subjects = set_1.intersection(set_2)
    print(f'Intersection {comb[0]} & {comb[1]}: {len(common_subjects)} subjects')
    df.loc[(comb[0], comb[1]), 'V04'] = len(common_subjects)

# =========================
# DataFrame 2: total de sujetos por modalidad
# =========================
df2 = pd.DataFrame(index=list_modalities, columns=['V04','V06','V08','V10'], dtype=int)
df_total_images = pd.DataFrame(index=list_modalities, columns=['Total_Images_PD_V04', 'Total_Images_PD_V06', 'Total_Images_PD_V08', 'Total_Images_PD_V10', 'Total_Images_PD_V12'], dtype=int)
for modality in list_modalities:
    set_modality = set(dict_modal_subjects[modality])
    print(f'Total subjects in {modality}: {len(set_modality)}')
    df2.loc[modality, 'V04'] = len(set_modality)
    df_total_images.loc[modality,'Total_Images_PD_V04'] = dict_images_subjects[modality]

Intersection DaTScan & fMRI: 169 subjects
Intersection DaTScan & DTI: 326 subjects
Intersection DaTScan & MRI_PD: 279 subjects
Intersection DaTScan & MRI_T1: 381 subjects
Intersection DaTScan & MRI_T2: 380 subjects
Intersection DaTScan & PET: 27 subjects
Intersection DaTScan & CT: 0 subjects
Intersection fMRI & DTI: 176 subjects
Intersection fMRI & MRI_PD: 90 subjects
Intersection fMRI & MRI_T1: 181 subjects
Intersection fMRI & MRI_T2: 181 subjects
Intersection fMRI & PET: 10 subjects
Intersection fMRI & CT: 0 subjects
Intersection DTI & MRI_PD: 243 subjects
Intersection DTI & MRI_T1: 350 subjects
Intersection DTI & MRI_T2: 351 subjects
Intersection DTI & PET: 9 subjects
Intersection DTI & CT: 0 subjects
Intersection MRI_PD & MRI_T1: 300 subjects
Intersection MRI_PD & MRI_T2: 300 subjects
Intersection MRI_PD & PET: 5 subjects
Intersection MRI_PD & CT: 0 subjects
Intersection MRI_T1 & MRI_T2: 414 subjects
Intersection MRI_T1 & PET: 14 subjects
Intersection MRI_T1 & CT: 0 subjects
Intersection MRI_T2 & PET: 14 subjects
Intersection MRI_T2 & CT: 0 subjects
Intersection PET & CT: 6 subjects
Total subjects in DaTScan: 576
Total subjects in fMRI: 182
Total subjects in DTI: 351
Total subjects in MRI_PD: 301
Total subjects in MRI_T1: 416
Total subjects in MRI_T2: 415
Total subjects in PET: 40
Total subjects in CT: 6

In [14]:
df

                         V04  V06  V08  V10
Modality_1 Modality_2
DaTScan    fMRI        169.0  NaN  NaN  NaN
           DTI         326.0  NaN  NaN  NaN
           MRI_PD      279.0  NaN  NaN  NaN
           MRI_T1      381.0  NaN  NaN  NaN
           MRI_T2      380.0  NaN  NaN  NaN
           PET          27.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
fMRI       DTI         176.0  NaN  NaN  NaN
           MRI_PD       90.0  NaN  NaN  NaN
           MRI_T1      181.0  NaN  NaN  NaN
           MRI_T2      181.0  NaN  NaN  NaN
           PET          10.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
DTI        MRI_PD      243.0  NaN  NaN  NaN
           MRI_T1      350.0  NaN  NaN  NaN
           MRI_T2      351.0  NaN  NaN  NaN
           PET           9.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
MRI_PD     MRI_T1      300.0  NaN  NaN  NaN
           MRI_T2      300.0  NaN  NaN  NaN
           PET           5.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
MRI_T1     MRI_T2      414.0  NaN  NaN  NaN
           PET          14.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
MRI_T2     PET          14.0  NaN  NaN  NaN
           CT            0.0  NaN  NaN  NaN
PET        CT            6.0  NaN  NaN  NaN

In [15]:
df2

           V04  V06  V08  V10
DaTScan  576.0  NaN  NaN  NaN
fMRI     182.0  NaN  NaN  NaN
DTI      351.0  NaN  NaN  NaN
MRI_PD   301.0  NaN  NaN  NaN
MRI_T1   416.0  NaN  NaN  NaN
MRI_T2   415.0  NaN  NaN  NaN
PET       40.0  NaN  NaN  NaN
CT         6.0  NaN  NaN  NaN

In [16]:
df_total_images

,Total_Images_PD_V04,Total_Images_PD_V06,Total_Images_PD_V08,Total_Images_PD_V10,Total_Images_PD_V12
DaTScan,1154.0,NaN,NaN,NaN,NaN
fMRI,385.0,NaN,NaN,NaN,NaN
DTI,2797.0,NaN,NaN,NaN,NaN
MRI_PD,645.0,NaN,NaN,NaN,NaN
MRI_T1,2130.0,NaN,NaN,NaN,NaN
MRI_T2,523.0,NaN,NaN,NaN,NaN
PET,94.0,NaN,NaN,NaN,NaN
CT,7.0,NaN,NaN,NaN,NaN

## V06

### Data Modalities

#### CT

In [17]:
ct_v06=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/CT/CT_images_V06.csv',sep=';', dtype=str)
ct_v06 = ct_v06[ct_v06['Subject ID'].isin(PATNOs)]
print(f"Total PATNOs with CT V06 images: {ct_v06['Subject ID'].nunique()}")
ct_v06.head(3)

Total PATNOs with CT V06 images: 7

  Subject ID Visit ID Sex   Age             Description      Type
0       3123      V06   M  71.3           CTAC 3D BRAIN  Original
1       3123      NaN   M  71.3           CTAC 3D BRAIN  Original
2       3125      NaN   M  48.1  Recon 2: CTAC 3D BRAIN  Original

#### DaTScan

In [18]:
datscan_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DaTScan/DaTScan_image_V06.csv', sep=';',dtype=str)
datscan_v06 = datscan_v06[datscan_v06['Subject ID'].isin(PATNOs)]
print(f'DaTScan V06 shape: {datscan_v06.shape}')
datscan_v06.head(3)

DaTScan V06 shape: (964, 6)

,Subject ID,Visit ID,Sex,Age,Description,Type
0,100001,V06,M,69.5,DaT Brain Tomo,Original
1,100001,NaN,M,69.5,Reconstructed DaTSCAN <- DaT Brain Tomo,Pre-processed
2,100006,NaN,F,57.9,Symbia PPMI 2.0,Original

#### fMRI

In [19]:
fmri_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/fMRI/fMRI_images_V06.csv', sep=';',dtype=str)
fmri_v06 = fmri_v06[fmri_v06['Subject ID'].isin(PATNOs)]
print(f'fMRI V06 shape: {fmri_v06.shape}')
fmri_v06.head(3)

fMRI V06 shape: (189, 6)

  Subject ID Visit ID Sex   Age Description      Type
0     100006      V06   F  57.9   rsfMRI_PA  Original
1     100006      NaN   F  57.9   rsfMRI_AP  Original
2     100007      NaN   M  69.5   rsfMRI_PA  Original

#### DTI

In [20]:
dti_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DTI/DTI_images_V06.csv', sep=';',dtype=str)
dti_v06 = dti_v06[dti_v06['Subject ID'].isin(PATNOs)]
print(f'DTI V06 shape: {dti_v06.shape}')
dti_v06.head(3)

DTI V06 shape: (1923, 6)

  Subject ID Visit ID Sex   Age         Description      Type
0     100006      V06   F  57.9        DTI_revB0_AP  Original
1     100006      NaN   F  57.9           DTI_B0_PA  Original
2     100006      NaN   F  57.9  DTI_B2000_64dir_PA  Original

#### MRI PD

In [21]:
mri_PD_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI PD/MRI_PD_images_V06.csv', sep=';',dtype=str)
mri_PD_v06 = mri_PD_v06[mri_PD_v06['Subject ID'].isin(PATNOs)]
print(f'MRI PD V06 shape: {mri_PD_v06.shape}')
mri_PD_v06.head(3)

MRI PD V06 shape: (404, 6)

,Subject ID,Visit ID,Sex,Age,Description,Type
0,100001,V06,M,69.5,L>R RESTING STATE FMRI ep2d_fid_basic_bold,Original
1,100001,NaN,M,69.5,R>L RESTING STATE FMRI ep2d_fid_basic_bold,Original
2,100006,NaN,F,57.9,3D T1 _weighted,Original

#### MRI T1

In [22]:
mri_T1_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T1/MRI_T1_images_V06.csv', sep=';',dtype=str)
mri_T1_v06 = mri_T1_v06[mri_T1_v06['Subject ID'].isin(PATNOs)]
print(f'MRI T1 V06 shape: {mri_T1_v06.shape}')
mri_T1_v06.head(3)

MRI T1 V06 shape: (1105, 6)

  Subject ID Visit ID Sex   Age    Description      Type
0     100001      V06   M  69.5  SAG 3D MPRAGE  Original
1     100001      NaN   M  69.5   AX T2 GRE MT  Original
2     100001      NaN   M  69.5   AX T2 GRE MT  Original

#### MRI T2

In [23]:
mri_T2_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T2/MRI_T2_images_V06.csv', sep=';',dtype=str)
mri_T2_v06 = mri_T2_v06[mri_T2_v06['Subject ID'].isin(PATNOs)]
print(f'MRI T2 V06 shape: {mri_T2_v06.shape}')
mri_T2_v06.head(3)

MRI T2 V06 shape: (330, 5)

  Subject ID Sex   Age         Description      Type
0     100001   M  69.5     3D T2 SAG FLAIR  Original
1     100001   M  69.5  3D T2 SAG FLAIR_ND  Original
2     100006   F  57.9         3D T2 FLAIR  Original

#### PET

In [24]:
pet_v06 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/PET/PET_image_V06.csv', sep=';',dtype=str)
pet_v06 = pet_v06[pet_v06['Subject ID'].isin(PATNOs)]
print(f'PET V06 shape: {pet_v06.shape}')
pet_v06.head(3)

PET V06 shape: (51, 6)

  Subject ID Visit ID Sex   Age                      Description      Type
0     101748      V06   F  64.8  AV 133 Delay 4i/16s- unfiltered  Original
1     101748      NaN   F  64.8    AV 133 Delay 4i/16s- filtered  Original
2     103813      NaN   F  66.8             BRAIN AC- unfiltered  Original

### Combinations of modalities in V06

In [25]:
dict_modal_subjects = {'DaTScan':datscan_v06['Subject ID'].unique(),
                'fMRI':fmri_v06['Subject ID'].unique(),
                'DTI':dti_v06['Subject ID'].unique(),
                'MRI_PD':mri_PD_v06['Subject ID'].unique(),
                'MRI_T1':mri_T1_v06['Subject ID'].unique(), 
                'MRI_T2':mri_T2_v06['Subject ID'].unique(), 
                'PET':pet_v06['Subject ID'].unique(),
                'CT':ct_v06['Subject ID'].unique()}

dict_images_subjects = {'DaTScan':datscan_v06['Subject ID'].shape[0],
                'fMRI':fmri_v06['Subject ID'].shape[0],
                'DTI':dti_v06['Subject ID'].shape[0],
                'MRI_PD':mri_PD_v06['Subject ID'].shape[0],
                'MRI_T1':mri_T1_v06['Subject ID'].shape[0], 
                'MRI_T2':mri_T2_v06['Subject ID'].shape[0], 
                'PET':pet_v06['Subject ID'].shape[0],
                'CT':ct_v06['Subject ID'].shape[0]}

list_modalities = list(dict_modal_subjects.keys())

# =========================
# DataFrame 1: intersecciones entre modalidades (MultiIndex)
# =========================
combinations_keys = list(combinations(list_modalities, 2))


for comb in combinations_keys:
    set_1 = set(dict_modal_subjects[comb[0]])
    set_2 = set(dict_modal_subjects[comb[1]])
    common_subjects = set_1.intersection(set_2)
    print(f'Intersection {comb[0]} & {comb[1]}: {len(common_subjects)} subjects')
    df.loc[(comb[0], comb[1]), 'V06'] = len(common_subjects)

# =========================
# DataFrame 2: total de sujetos por modalidad
# =========================

for modality in list_modalities:
    set_modality = set(dict_modal_subjects[modality])
    print(f'Modality {modality}: {len(set_modality)} subjects')
    df2.loc[modality, 'V06'] = len(set_modality)
    df_total_images.loc[modality,'Total_Images_PD_V06'] = dict_images_subjects[modality]

Intersection DaTScan & fMRI: 92 subjects
Intersection DaTScan & DTI: 176 subjects
Intersection DaTScan & MRI_PD: 170 subjects
Intersection DaTScan & MRI_T1: 219 subjects
Intersection DaTScan & MRI_T2: 219 subjects
Intersection DaTScan & PET: 25 subjects
Intersection DaTScan & CT: 7 subjects
Intersection fMRI & DTI: 87 subjects
Intersection fMRI & MRI_PD: 47 subjects
Intersection fMRI & MRI_T1: 97 subjects
Intersection fMRI & MRI_T2: 96 subjects
Intersection fMRI & PET: 9 subjects
Intersection fMRI & CT: 3 subjects
Intersection DTI & MRI_PD: 144 subjects
Intersection DTI & MRI_T1: 190 subjects
Intersection DTI & MRI_T2: 190 subjects
Intersection DTI & PET: 4 subjects
Intersection DTI & CT: 3 subjects
Intersection MRI_PD & MRI_T1: 185 subjects
Intersection MRI_PD & MRI_T2: 185 subjects
Intersection MRI_PD & PET: 3 subjects
Intersection MRI_PD & CT: 3 subjects
Intersection MRI_T1 & MRI_T2: 239 subjects
Intersection MRI_T1 & PET: 9 subjects
Intersection MRI_T1 & CT: 3 subjects
Intersection MRI_T2 & PET: 9 subjects
Intersection MRI_T2 & CT: 3 subjects
Intersection PET & CT: 7 subjects
Modality DaTScan: 457 subjects
Modality fMRI: 97 subjects
Modality DTI: 191 subjects
Modality MRI_PD: 186 subjects
Modality MRI_T1: 241 subjects
Modality MRI_T2: 240 subjects
Modality PET: 26 subjects
Modality CT: 7 subjects

In [26]:
df

                         V04    V06  V08  V10
Modality_1 Modality_2
DaTScan    fMRI        169.0   92.0  NaN  NaN
           DTI         326.0  176.0  NaN  NaN
           MRI_PD      279.0  170.0  NaN  NaN
           MRI_T1      381.0  219.0  NaN  NaN
           MRI_T2      380.0  219.0  NaN  NaN
           PET          27.0   25.0  NaN  NaN
           CT            0.0    7.0  NaN  NaN
fMRI       DTI         176.0   87.0  NaN  NaN
           MRI_PD       90.0   47.0  NaN  NaN
           MRI_T1      181.0   97.0  NaN  NaN
           MRI_T2      181.0   96.0  NaN  NaN
           PET          10.0    9.0  NaN  NaN
           CT            0.0    3.0  NaN  NaN
DTI        MRI_PD      243.0  144.0  NaN  NaN
           MRI_T1      350.0  190.0  NaN  NaN
           MRI_T2      351.0  190.0  NaN  NaN
           PET           9.0    4.0  NaN  NaN
           CT            0.0    3.0  NaN  NaN
MRI_PD     MRI_T1      300.0  185.0  NaN  NaN
           MRI_T2      300.0  185.0  NaN  NaN
           PET           5.0    3.0  NaN  NaN
           CT            0.0    3.0  NaN  NaN
MRI_T1     MRI_T2      414.0  239.0  NaN  NaN
           PET          14.0    9.0  NaN  NaN
           CT            0.0    3.0  NaN  NaN
MRI_T2     PET          14.0    9.0  NaN  NaN
           CT            0.0    3.0  NaN  NaN
PET        CT            6.0    7.0  NaN  NaN

In [27]:
df2

           V04    V06  V08  V10
DaTScan  576.0  457.0  NaN  NaN
fMRI     182.0   97.0  NaN  NaN
DTI      351.0  191.0  NaN  NaN
MRI_PD   301.0  186.0  NaN  NaN
MRI_T1   416.0  241.0  NaN  NaN
MRI_T2   415.0  240.0  NaN  NaN
PET       40.0   26.0  NaN  NaN
CT         6.0    7.0  NaN  NaN

In [28]:
df_total_images

,Total_Images_PD_V04,Total_Images_PD_V06,Total_Images_PD_V08,Total_Images_PD_V10,Total_Images_PD_V12
DaTScan,1154.0,964.0,NaN,NaN,NaN
fMRI,385.0,189.0,NaN,NaN,NaN
DTI,2797.0,1923.0,NaN,NaN,NaN
MRI_PD,645.0,404.0,NaN,NaN,NaN
MRI_T1,2130.0,1105.0,NaN,NaN,NaN
MRI_T2,523.0,330.0,NaN,NaN,NaN
PET,94.0,51.0,NaN,NaN,NaN
CT,7.0,13.0,NaN,NaN,NaN

## V08

### Data Modalities

#### CT

In [29]:
ct_v08=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/CT/CT_images_V08.csv',sep=';', dtype=str)
ct_v08 = ct_v08[ct_v08['Subject ID'].isin(PATNOs)]
print(f"Total PATNOs with CT V08 images: {ct_v08['Subject ID'].nunique()}")
ct_v08.head(3)

Total PATNOs with CT V08 images: 7

  Subject ID Visit ID Sex   Age     Description      Type
0       3223      V08   M  69.5  AC CT Brain 50  Original
1       3223      NaN   M  69.5  AC CT Brain 50  Original
2       3230      NaN   M  72.9  AC CT Brain 50  Original

#### DaTScan

In [30]:
datscan_v08 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DaTScan/DaTScan_image_V08.csv', sep=';',dtype=str)
datscan_v08 = datscan_v08[datscan_v08['Subject ID'].isin(PATNOs)]
print(f'DaTScan V08 shape: {datscan_v08.shape}')
datscan_v08.head(3)

DaTScan V08 shape: (2, 6)

,Subject ID,Visit ID,Sex,Age,Description,Type
0,57880,V08,M,65.0,PPMI DATSCAN,Original
1,57880,NaN,M,65.0,Reconstructed DaTSCAN <- PPMI DATSCAN,Pre-processed

#### fMRI

In [31]:
# NO TENGO fMRI V08

#### DTI

In [32]:
# NO TENGO fMRI V08

#### MRI PD

In [33]:
# NO MRI PD V08 available

#### MRI T1

In [34]:
# No MRI T1 V08 available

#### MRI T2

In [35]:
# No MRI T2 V08 available

#### PET

In [36]:
pet_v08 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/PET/PET_image_V08.csv', sep=';',dtype=str)
pet_v08 = pet_v08[pet_v08['Subject ID'].isin(PATNOs)]
print(f'PET V08 shape: {pet_v08.shape}')
pet_v08.head(3)

PET V08 shape: (52, 6)

  Subject ID Visit ID Sex   Age Description      Type
0       3223      V08   M  69.5        EM90  Original
1       3223      NaN   M  69.5        EM90  Original
2       3223      NaN   M  69.5       EM105  Original

### Combinations of modalities in V08

In [37]:
dict_modal_subjects = {'DaTScan':datscan_v08['Subject ID'].unique(),
                'fMRI':[],
                'DTI':[],
                'MRI_PD':[],
                'MRI_T1':[],
                'MRI_T2':[],
                'PET':pet_v08['Subject ID'].unique(),
                'CT':ct_v08['Subject ID'].unique()}

dict_images_subjects = {'DaTScan':datscan_v08['Subject ID'].shape[0],
                'fMRI':0,
                'DTI':0,
                'MRI_PD':0,
                'MRI_T1':0,
                'MRI_T2':0,
                'PET':pet_v08['Subject ID'].shape[0],
                'CT':ct_v08['Subject ID'].shape[0]}

list_modalities = list(dict_modal_subjects.keys())

# =========================
# DataFrame 1: intersecciones entre modalidades (MultiIndex)
# =========================
combinations_keys = list(combinations(list_modalities, 2))


for comb in combinations_keys:
    set_1 = set(dict_modal_subjects[comb[0]])
    set_2 = set(dict_modal_subjects[comb[1]])
    common_subjects = set_1.intersection(set_2)
    print(f'Intersection {comb[0]} & {comb[1]}: {len(common_subjects)} subjects')
    df.loc[(comb[0], comb[1]), 'V08'] = len(common_subjects)

# =========================
# DataFrame 2: total de sujetos por modalidad
# =========================

for modality in list_modalities:
    set_modality = set(dict_modal_subjects[modality])
    print(f'Modality {modality}: {len(set_modality)} subjects')
    df2.loc[modality, 'V08'] = len(set_modality)
    df_total_images.loc[modality,'Total_Images_PD_V08'] = dict_images_subjects[modality]

Intersection DaTScan & fMRI: 0 subjects
Intersection DaTScan & DTI: 0 subjects
Intersection DaTScan & MRI_PD: 0 subjects
Intersection DaTScan & MRI_T1: 0 subjects
Intersection DaTScan & MRI_T2: 0 subjects
Intersection DaTScan & PET: 0 subjects
Intersection DaTScan & CT: 0 subjects
Intersection fMRI & DTI: 0 subjects
Intersection fMRI & MRI_PD: 0 subjects
Intersection fMRI & MRI_T1: 0 subjects
Intersection fMRI & MRI_T2: 0 subjects
Intersection fMRI & PET: 0 subjects
Intersection fMRI & CT: 0 subjects
Intersection DTI & MRI_PD: 0 subjects
Intersection DTI & MRI_T1: 0 subjects
Intersection DTI & MRI_T2: 0 subjects
Intersection DTI & PET: 0 subjects
Intersection DTI & CT: 0 subjects
Intersection MRI_PD & MRI_T1: 0 subjects
Intersection MRI_PD & MRI_T2: 0 subjects
Intersection MRI_PD & PET: 0 subjects
Intersection MRI_PD & CT: 0 subjects
Intersection MRI_T1 & MRI_T2: 0 subjects
Intersection MRI_T1 & PET: 0 subjects
Intersection MRI_T1 & CT: 0 subjects
Intersection MRI_T2 & PET: 0 subjects
Intersection MRI_T2 & CT: 0 subjects
Intersection PET & CT: 7 subjects
Modality DaTScan: 1 subjects
Modality fMRI: 0 subjects
Modality DTI: 0 subjects
Modality MRI_PD: 0 subjects
Modality MRI_T1: 0 subjects
Modality MRI_T2: 0 subjects
Modality PET: 23 subjects
Modality CT: 7 subjects

In [38]:
df

                         V04    V06  V08  V10
Modality_1 Modality_2
DaTScan    fMRI        169.0   92.0  0.0  NaN
           DTI         326.0  176.0  0.0  NaN
           MRI_PD      279.0  170.0  0.0  NaN
           MRI_T1      381.0  219.0  0.0  NaN
           MRI_T2      380.0  219.0  0.0  NaN
           PET          27.0   25.0  0.0  NaN
           CT            0.0    7.0  0.0  NaN
fMRI       DTI         176.0   87.0  0.0  NaN
           MRI_PD       90.0   47.0  0.0  NaN
           MRI_T1      181.0   97.0  0.0  NaN
           MRI_T2      181.0   96.0  0.0  NaN
           PET          10.0    9.0  0.0  NaN
           CT            0.0    3.0  0.0  NaN
DTI        MRI_PD      243.0  144.0  0.0  NaN
           MRI_T1      350.0  190.0  0.0  NaN
           MRI_T2      351.0  190.0  0.0  NaN
           PET           9.0    4.0  0.0  NaN
           CT            0.0    3.0  0.0  NaN
MRI_PD     MRI_T1      300.0  185.0  0.0  NaN
           MRI_T2      300.0  185.0  0.0  NaN
           PET           5.0    3.0  0.0  NaN
           CT            0.0    3.0  0.0  NaN
MRI_T1     MRI_T2      414.0  239.0  0.0  NaN
           PET          14.0    9.0  0.0  NaN
           CT            0.0    3.0  0.0  NaN
MRI_T2     PET          14.0    9.0  0.0  NaN
           CT            0.0    3.0  0.0  NaN
PET        CT            6.0    7.0  7.0  NaN

In [39]:
df2

           V04    V06   V08  V10
DaTScan  576.0  457.0   1.0  NaN
fMRI     182.0   97.0   0.0  NaN
DTI      351.0  191.0   0.0  NaN
MRI_PD   301.0  186.0   0.0  NaN
MRI_T1   416.0  241.0   0.0  NaN
MRI_T2   415.0  240.0   0.0  NaN
PET       40.0   26.0  23.0  NaN
CT         6.0    7.0   7.0  NaN

In [40]:
df_total_images

,Total_Images_PD_V04,Total_Images_PD_V06,Total_Images_PD_V08,Total_Images_PD_V10,Total_Images_PD_V12
DaTScan,1154.0,964.0,2.0,NaN,NaN
fMRI,385.0,189.0,0.0,NaN,NaN
DTI,2797.0,1923.0,0.0,NaN,NaN
MRI_PD,645.0,404.0,0.0,NaN,NaN
MRI_T1,2130.0,1105.0,0.0,NaN,NaN
MRI_T2,523.0,330.0,0.0,NaN,NaN
PET,94.0,51.0,52.0,NaN,NaN
CT,7.0,13.0,11.0,NaN,NaN

## V10

### Data Modalities

#### CT

In [41]:
ct_v10=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/CT/CT_images_V10.csv',sep=';', dtype=str)
ct_v10 = ct_v10[ct_v10['Subject ID'].isin(PATNOs)]
print(f"Total PATNOs with CT V10 images: {ct_v10['Subject ID'].nunique()}")
ct_v10.head(3)

Total PATNOs with CT V10 images: 1

  Subject ID Visit ID Sex   Age          Description      Type
0       3900      V10   M  75.9      H30S med smooth  Original
1       3900      NaN   M  75.9  AC_CT H19S v smooth  Original

#### DaTScan

In [42]:
datscan_v10= pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DaTScan/DaTScan_image_V10.csv', sep=';',dtype=str)
datscan_v10 = datscan_v10[datscan_v10['Subject ID'].isin(PATNOs)]
print(f'DaTScan V10 shape: {datscan_v10.shape}')
datscan_v10.head(3)

DaTScan V10 shape: (562, 6)

  Subject ID Visit ID Sex   Age            Description           Type
0     100001      V10   M  71.3           I123 DaTScan       Original
1     100001      NaN   M  71.3  Reconstructed DaTSCAN  Pre-processed
2       3001      NaN   M  69.2             PROJECTION       Original

#### fMRI

In [43]:
fmri_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/fMRI/fMRI_images_V10.csv', sep=';',dtype=str)
fmri_v10 = fmri_v10[fmri_v10['Subject ID'].isin(PATNOs)]
print(f'fMRI V10 shape: {fmri_v10.shape}')
fmri_v10.head(3)

fMRI V10 shape: (99, 6)

  Subject ID Visit ID Sex   Age         Description      Type
0     100001      V10   M  71.3         rsFMRI ep2d  Original
1     100001      NaN   M  71.3   rsFMRI ep2dREPEAT  Original
3       3108      NaN   F  53.8  ep2d_RESTING_STATE  Original

#### DTI

In [44]:
dti_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/DTI/DTI_images_V10.csv', sep=';',dtype=str)
dti_v10 = dti_v10[dti_v10['Subject ID'].isin(PATNOs)]
print(f'DTI V10 shape: {dti_v10.shape}')
dti_v10.head(3)

DTI V10 shape: (1062, 6)

   Subject ID Visit ID Sex   Age Description      Type
0      100001      V10   M  71.3      Ax DTI  Original
23       3108      NaN   F  53.8   DTI_gated  Original
24       3108      NaN   F  53.8   DTI_gated  Original

#### MRI PD

In [45]:
mri_PD_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI PD/MRI_PD_iamges_V10.csv', sep=';',dtype=str)
mri_PD_v10 = mri_PD_v10[mri_PD_v10['Subject ID'].isin(PATNOs)]
print(f'MRI PD V10 shape: {mri_PD_v10.shape}')
mri_PD_v10.head(3)

MRI PD V10 shape: (151, 6)

   Subject ID Visit ID Sex   Age         Description      Type
3        3108      NaN   F  53.8  Axial PD-T2 TSE FS  Original
9        3123      NaN   M  73.3  Axial PD-T2 TSE FS  Original
11       3125      NaN   M  50.0  Axial PD-T2 TSE FS  Original

#### MRI T1

In [46]:
mri_T1_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T1/MRI_T1_images_V10.csv', sep=';',dtype=str)
mri_T1_v10 = mri_T1_v10[mri_T1_v10['Subject ID'].isin(PATNOs)]
print(f'MRI T1 V10 shape: {mri_T1_v10.shape}')
mri_T1_v10.head(3)

MRI T1 V10 shape: (440, 6)

  Subject ID Visit ID Sex   Age      Description      Type
0     100001      V10   M  71.3  SAG 3D T1 FSPGR  Original
1     100001      NaN   M  71.3         B0rf Map  Original
2     100001      NaN   M  71.3  AXIAL 2D GRE-MT  Original

#### MRI T2

In [47]:
mri_T2_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/MRI T2/MRI_T2_images_V10.csv', sep=';',dtype=str)
mri_T2_v10 = mri_T2_v10[mri_T2_v10['Subject ID'].isin(PATNOs)]
print(f'MRI T2 V10 shape: {mri_T2_v10.shape}')
mri_T2_v10.head(3)

MRI T2 V10 shape: (158, 5)

,Subject ID,Sex,Age,Description,Type
0,100001,M,71.3,Sag 3D T2 FLAIR,Original
6,3108,F,53.8,Axial PD-T2 TSE FS,Original
12,3123,M,73.3,T2 in T1-anatomical space <- Sag MPRAGE GRAPPA,Pre-processed

#### PET

In [48]:
pet_v10 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/PET/PET_image_V10.csv', sep=';',dtype=str)
pet_v10 = pet_v10[pet_v10['Subject ID'].isin(PATNOs)]
print(f'PET V10 shape: {pet_v10.shape}')
pet_v10.head(3)

PET V10 shape: (17, 6)

  Subject ID Visit ID Sex   Age                    Description      Type
0       3418      V10   M  59.0                 TX Scan 4i/16s  Original
1       3418      NaN   M  59.0  18-F florbetaben 4i/16s  AV45  Original
2       3418      NaN   M  59.0        18-F florbetaben 4i/16s  Original

### Combinations of modalities in V10

In [49]:
dict_modal_subjects = {'DaTScan':datscan_v10['Subject ID'].unique(),
                        'fMRI':fmri_v10['Subject ID'].unique(),
                        'DTI':dti_v10['Subject ID'].unique(),
                        'MRI_PD':mri_PD_v10['Subject ID'].unique(),
                        'MRI_T1':mri_T1_v10['Subject ID'].unique(),
                        'MRI_T2':mri_T2_v10['Subject ID'].unique(),
                        'PET':pet_v10['Subject ID'].unique(),
                        'CT':ct_v10['Subject ID'].unique()}

dict_images_subjects = {'DaTScan':datscan_v10['Subject ID'].shape[0],
                        'fMRI':fmri_v10['Subject ID'].shape[0],
                        'DTI':dti_v10['Subject ID'].shape[0],
                        'MRI_PD':mri_PD_v10['Subject ID'].shape[0],
                        'MRI_T1':mri_T1_v10['Subject ID'].shape[0],
                        'MRI_T2':mri_T2_v10['Subject ID'].shape[0],
                        'PET':pet_v10['Subject ID'].shape[0],
                        'CT':ct_v10['Subject ID'].shape[0]}

list_modalities = list(dict_modal_subjects.keys())

# =========================
# DataFrame 1: intersecciones entre modalidades (MultiIndex)
# =========================
combinations_keys = list(combinations(list_modalities, 2))
for comb in combinations_keys:
    set_1 = set(dict_modal_subjects[comb[0]])
    set_2 = set(dict_modal_subjects[comb[1]])
    common_subjects = set_1.intersection(set_2)
    print(f'Intersection {comb[0]} & {comb[1]}: {len(common_subjects)} subjects')
    df.loc[(comb[0], comb[1]), 'V10'] = len(common_subjects)

# =========================
# DataFrame 2: total de sujetos por modalidad
# =========================
for modality in list_modalities:
    set_modality = set(dict_modal_subjects[modality])
    print(f'Total subjects in {modality}: {len(set_modality)}')
    df2.loc[modality, 'V10'] = len(set_modality)
    df_total_images.loc[modality,'Total_Images_PD_V10'] = dict_images_subjects[modality]

Intersection DaTScan & fMRI: 54 subjects
Intersection DaTScan & DTI: 76 subjects
Intersection DaTScan & MRI_PD: 77 subjects
Intersection DaTScan & MRI_T1: 82 subjects
Intersection DaTScan & MRI_T2: 81 subjects
Intersection DaTScan & PET: 11 subjects
Intersection DaTScan & CT: 0 subjects
Intersection fMRI & DTI: 62 subjects
Intersection fMRI & MRI_PD: 57 subjects
Intersection fMRI & MRI_T1: 61 subjects
Intersection fMRI & MRI_T2: 61 subjects
Intersection fMRI & PET: 0 subjects
Intersection fMRI & CT: 0 subjects
Intersection DTI & MRI_PD: 79 subjects
Intersection DTI & MRI_T1: 84 subjects
Intersection DTI & MRI_T2: 83 subjects
Intersection DTI & PET: 0 subjects
Intersection DTI & CT: 0 subjects
Intersection MRI_PD & MRI_T1: 88 subjects
Intersection MRI_PD & MRI_T2: 87 subjects
Intersection MRI_PD & PET: 0 subjects
Intersection MRI_PD & CT: 0 subjects
Intersection MRI_T1 & MRI_T2: 92 subjects
Intersection MRI_T1 & PET: 0 subjects
Intersection MRI_T1 & CT: 0 subjects
Intersection MRI_T2 & PET: 0 subjects
Intersection MRI_T2 & CT: 0 subjects
Intersection PET & CT: 1 subjects
Total subjects in DaTScan: 244
Total subjects in fMRI: 62
Total subjects in DTI: 86
Total subjects in MRI_PD: 89
Total subjects in MRI_T1: 94
Total subjects in MRI_T2: 92
Total subjects in PET: 12
Total subjects in CT: 1

In [50]:
df

                         V04    V06  V08   V10
Modality_1 Modality_2
DaTScan    fMRI        169.0   92.0  0.0  54.0
           DTI         326.0  176.0  0.0  76.0
           MRI_PD      279.0  170.0  0.0  77.0
           MRI_T1      381.0  219.0  0.0  82.0
           MRI_T2      380.0  219.0  0.0  81.0
           PET          27.0   25.0  0.0  11.0
           CT            0.0    7.0  0.0   0.0
fMRI       DTI         176.0   87.0  0.0  62.0
           MRI_PD       90.0   47.0  0.0  57.0
           MRI_T1      181.0   97.0  0.0  61.0
           MRI_T2      181.0   96.0  0.0  61.0
           PET          10.0    9.0  0.0   0.0
           CT            0.0    3.0  0.0   0.0
DTI        MRI_PD      243.0  144.0  0.0  79.0
           MRI_T1      350.0  190.0  0.0  84.0
           MRI_T2      351.0  190.0  0.0  83.0
           PET           9.0    4.0  0.0   0.0
           CT            0.0    3.0  0.0   0.0
MRI_PD     MRI_T1      300.0  185.0  0.0  88.0
           MRI_T2      300.0  185.0  0.0  87.0
           PET           5.0    3.0  0.0   0.0
           CT            0.0    3.0  0.0   0.0
MRI_T1     MRI_T2      414.0  239.0  0.0  92.0
           PET          14.0    9.0  0.0   0.0
           CT            0.0    3.0  0.0   0.0
MRI_T2     PET          14.0    9.0  0.0   0.0
           CT            0.0    3.0  0.0   0.0
PET        CT            6.0    7.0  7.0   1.0

In [51]:
df2

           V04    V06   V08    V10
DaTScan  576.0  457.0   1.0  244.0
fMRI     182.0   97.0   0.0   62.0
DTI      351.0  191.0   0.0   86.0
MRI_PD   301.0  186.0   0.0   89.0
MRI_T1   416.0  241.0   0.0   94.0
MRI_T2   415.0  240.0   0.0   92.0
PET       40.0   26.0  23.0   12.0
CT         6.0    7.0   7.0    1.0

In [52]:
df_total_images

,Total_Images_PD_V04,Total_Images_PD_V06,Total_Images_PD_V08,Total_Images_PD_V10,Total_Images_PD_V12
DaTScan,1154.0,964.0,2.0,562.0,NaN
fMRI,385.0,189.0,0.0,99.0,NaN
DTI,2797.0,1923.0,0.0,1062.0,NaN
MRI_PD,645.0,404.0,0.0,151.0,NaN
MRI_T1,2130.0,1105.0,0.0,440.0,NaN
MRI_T2,523.0,330.0,0.0,158.0,NaN
PET,94.0,51.0,52.0,17.0,NaN
CT,7.0,13.0,11.0,2.0,NaN

## V12

### Data Modalities

# DaTScan / DTI / fMRI / MRI PD T1 T2

In [53]:
# No tengo V12 data available para DaTScan, fMRI, DTI, MRI PD, MRI T1, MRI T2

#### CT

In [54]:
ct_v12=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/CT/CT_images_V12.csv',sep=';', dtype=str)
ct_v12 = ct_v12[ct_v12['Subject ID'].isin(PATNOs)]
print(f"Total PATNOs with CT V12 images: {ct_v12['Subject ID'].nunique()}")
ct_v12.head(3)

Total PATNOs with CT V12 images: 2

  Subject ID Visit ID Sex   Age     Description      Type
0       3220      V12   F  78.5  AC CT Brain 50  Original
1       3469      NaN   M  62.5            CTAC  Original
2       3469      NaN   M  62.5            STND  Original

#### PET

In [55]:
pet_v12 = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/IMAGE_COVERAGE_ANALYSIS/IMG_Metadata_IDA_searcher/PET/PET_image_V12.csv', sep=';',dtype=str)
pet_v12 = pet_v12[pet_v12['Subject ID'].isin(PATNOs)]
print(f'PET V12 shape: {pet_v12.shape}')
pet_v12.head(3)

PET V12 shape: (5, 6)

  Subject ID Visit ID Sex   Age Description      Type
0       3220      V12   F  78.5       EM100  Original
1       3220      NaN   F  78.5       EM105  Original
2       3220      NaN   F  78.5        EM95  Original

### Combinations of modalities in V12

In [56]:
dict_modal_subjects = {'DaTScan':[],
                        'fMRI':[],
                        'DTI':[],
                        'MRI_PD':[],
                        'MRI_T1':[],
                        'MRI_T2':[],
                        'PET':pet_v12['Subject ID'].unique(),
                        'CT':ct_v12['Subject ID'].unique()}

dict_images_subjects = {'DaTScan':0,
                        'fMRI':0,
                        'DTI':0,
                        'MRI_PD':0,
                        'MRI_T1':0,
                        'MRI_T2':0,
                        'PET':pet_v12['Subject ID'].shape[0],
                        'CT':ct_v12['Subject ID'].shape[0]}

list_modalities = list(dict_modal_subjects.keys())

# =========================
# DataFrame 1: intersecciones entre modalidades (MultiIndex)
# =========================
combinations_keys = list(combinations(list_modalities, 2))
for comb in combinations_keys:
    set_1 = set(dict_modal_subjects[comb[0]])
    set_2 = set(dict_modal_subjects[comb[1]])
    common_subjects = set_1.intersection(set_2)
    print(f'Intersection {comb[0]} & {comb[1]}: {len(common_subjects)} subjects')
    df.loc[(comb[0], comb[1]), 'V12'] = len(common_subjects)

# =========================
# DataFrame 2: total de sujetos por modalidad
# =========================
for modality in list_modalities:
    set_modality = set(dict_modal_subjects[modality])
    print(f'Total subjects in {modality}: {len(set_modality)}')
    df2.loc[modality, 'V12'] = len(set_modality)
    df_total_images.loc[modality,'Total_Images_PD_V12'] = dict_images_subjects[modality]

Intersection DaTScan & fMRI: 0 subjects
Intersection DaTScan & DTI: 0 subjects
Intersection DaTScan & MRI_PD: 0 subjects
Intersection DaTScan & MRI_T1: 0 subjects
Intersection DaTScan & MRI_T2: 0 subjects
Intersection DaTScan & PET: 0 subjects
Intersection DaTScan & CT: 0 subjects
Intersection fMRI & DTI: 0 subjects
Intersection fMRI & MRI_PD: 0 subjects
Intersection fMRI & MRI_T1: 0 subjects
Intersection fMRI & MRI_T2: 0 subjects
Intersection fMRI & PET: 0 subjects
Intersection fMRI & CT: 0 subjects
Intersection DTI & MRI_PD: 0 subjects
Intersection DTI & MRI_T1: 0 subjects
Intersection DTI & MRI_T2: 0 subjects
Intersection DTI & PET: 0 subjects
Intersection DTI & CT: 0 subjects
Intersection MRI_PD & MRI_T1: 0 subjects
Intersection MRI_PD & MRI_T2: 0 subjects
Intersection MRI_PD & PET: 0 subjects
Intersection MRI_PD & CT: 0 subjects
Intersection MRI_T1 & MRI_T2: 0 subjects
Intersection MRI_T1 & PET: 0 subjects
Intersection MRI_T1 & CT: 0 subjects
Intersection MRI_T2 & PET: 0 subjects
Intersection MRI_T2 & CT: 0 subjects
Intersection PET & CT: 2 subjects
Total subjects in DaTScan: 0
Total subjects in fMRI: 0
Total subjects in DTI: 0
Total subjects in MRI_PD: 0
Total subjects in MRI_T1: 0
Total subjects in MRI_T2: 0
Total subjects in PET: 2
Total subjects in CT: 2

## TABLA FINAL

In [57]:
df['Total_Count'] = df[['V04', 'V06', 'V08', 'V10','V12']].sum(axis=1)
df

                         V04    V06  V08   V10  V12  Total_Count
Modality_1 Modality_2
DaTScan    fMRI        169.0   92.0  0.0  54.0  0.0        315.0
           DTI         326.0  176.0  0.0  76.0  0.0        578.0
           MRI_PD      279.0  170.0  0.0  77.0  0.0        526.0
           MRI_T1      381.0  219.0  0.0  82.0  0.0        682.0
           MRI_T2      380.0  219.0  0.0  81.0  0.0        680.0
           PET          27.0   25.0  0.0  11.0  0.0         63.0
           CT            0.0    7.0  0.0   0.0  0.0          7.0
fMRI       DTI         176.0   87.0  0.0  62.0  0.0        325.0
           MRI_PD       90.0   47.0  0.0  57.0  0.0        194.0
           MRI_T1      181.0   97.0  0.0  61.0  0.0        339.0
           MRI_T2      181.0   96.0  0.0  61.0  0.0        338.0
           PET          10.0    9.0  0.0   0.0  0.0         19.0
           CT            0.0    3.0  0.0   0.0  0.0          3.0
DTI        MRI_PD      243.0  144.0  0.0  79.0  0.0        466.0
           MRI_T1      350.0  190.0  0.0  84.0  0.0        624.0
           MRI_T2      351.0  190.0  0.0  83.0  0.0        624.0
           PET           9.0    4.0  0.0   0.0  0.0         13.0
           CT            0.0    3.0  0.0   0.0  0.0          3.0
MRI_PD     MRI_T1      300.0  185.0  0.0  88.0  0.0        573.0
           MRI_T2      300.0  185.0  0.0  87.0  0.0        572.0
           PET           5.0    3.0  0.0   0.0  0.0          8.0
           CT            0.0    3.0  0.0   0.0  0.0          3.0
MRI_T1     MRI_T2      414.0  239.0  0.0  92.0  0.0        745.0
           PET          14.0    9.0  0.0   0.0  0.0         23.0
           CT            0.0    3.0  0.0   0.0  0.0          3.0
MRI_T2     PET          14.0    9.0  0.0   0.0  0.0         23.0
           CT            0.0    3.0  0.0   0.0  0.0          3.0
PET        CT            6.0    7.0  7.0   1.0  2.0         23.0

In [58]:
df2['Total_Count'] = df2[['V04', 'V06', 'V08', 'V10','V12']].sum(axis=1)
df2

           V04    V06   V08    V10  V12  Total_Count
DaTScan  576.0  457.0   1.0  244.0  0.0       1278.0
fMRI     182.0   97.0   0.0   62.0  0.0        341.0
DTI      351.0  191.0   0.0   86.0  0.0        628.0
MRI_PD   301.0  186.0   0.0   89.0  0.0        576.0
MRI_T1   416.0  241.0   0.0   94.0  0.0        751.0
MRI_T2   415.0  240.0   0.0   92.0  0.0        747.0
PET       40.0   26.0  23.0   12.0  2.0        103.0
CT         6.0    7.0   7.0    1.0  2.0         23.0

In [59]:
df_total_images['Total_Images_PD_All_Visits'] = df_total_images[['Total_Images_PD_V04', 'Total_Images_PD_V06', 'Total_Images_PD_V08', 'Total_Images_PD_V10','Total_Images_PD_V12']].sum(axis=1)
df_total_images

,Total_Images_PD_V04,Total_Images_PD_V06,Total_Images_PD_V08,Total_Images_PD_V10,Total_Images_PD_V12,Total_Images_PD_All_Visits
DaTScan,1154.0,964.0,2.0,562.0,0.0,2682.0
fMRI,385.0,189.0,0.0,99.0,0.0,673.0
DTI,2797.0,1923.0,0.0,1062.0,0.0,5782.0
MRI_PD,645.0,404.0,0.0,151.0,0.0,1200.0
MRI_T1,2130.0,1105.0,0.0,440.0,0.0,3675.0
MRI_T2,523.0,330.0,0.0,158.0,0.0,1011.0
PET,94.0,51.0,52.0,17.0,5.0,219.0
CT,7.0,13.0,11.0,2.0,3.0,36.0